version: '3'

services:
  db:
    build:
      context: ./mysql
    restart : always
    command: --innodb-use-native-aio=0
    container_name: db
    tty: true
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=fullcycleDB
    networks:
      - nodenet

  app:
    build:
      context: node
    container_name: app
    networks:
      - nodenet
    volumes: 
      - ./node:/usr/src/app
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - db

  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - nodenet
    
networks:
  nodenet:
    driver: bridge

volumes:
  mysql: