
POST http://localhost:3000/clients HTTP/1.1
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john@j.com"
}

###

POST http://localhost:3000/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id": "87495b95-1c7f-4038-ae55-ab36ed6a9411"
}

###

POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
    "account_id_from": "02c08bd5-7ec2-45d9-8f27-8c3422927b6a",
    "account_id_to": "c98ed461-eb0c-47e3-b142-b5fbdf86dc41",
    "amount": 1
}

